name: Packer Build Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Application and Download Dependencies
        run: mvn clean compile

      - name: Run Integration Tests
        run: mvn test

      - name: Package the Application
        run: |
          mvn package -DskipTests
          mkdir -p artifact
          cp target/*.jar artifact/

      - name: Upload JAR File for Packer
        uses: actions/upload-artifact@v3
        with:
          name: myapp-jar
          path: artifact/

  packer-build:
    needs: build-test-package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp-jar
          path: artifact/

      - name: Install Packer
        uses: hashicorp/setup-packer@v1

      - name: Authenticate AWS
        run: aws configure set region us-east-1

      - name: Run Packer to Build Custom Image
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: packer build -var "db_url=$DB_URL" -var "db_username=$DB_USERNAME" -var "db_password=$DB_PASSWORD" packer/ubuntu.pkr.hcl
