name: Packer Build Workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] 
  workflow_dispatch:

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Package the Application
        run: |
          mvn package -DskipTests
          mkdir -p artifact
          cp target/*.jar artifact/

      - name: Upload JAR File for Packer
        uses: actions/upload-artifact@v4
        with:
          name: myapp-jar
          path: artifact/

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-jar
          path: artifact/

      - name: Install Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer Plugins
        run: packer init packer/ubuntu.pkr.hcl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEV_SA_KEY }}

      - name: Run Packer to Build & Share AWS & GCP Custom Images
        env:
          DB_USERNAME: ${{ secrets.CSYE_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.CSYE_DB_PASSWORD }}
          AWS_DEMO_ACCOUNT: ${{ secrets.AWS_DEMO_ACCOUNT_ID }}
          GCP_DEMO_PROJECT: ${{ secrets.GCP_DEMO_PROJECT_ID }}
        run: |
          packer build -on-error=abort \
            -var "db_username=$DB_USERNAME" \
            -var "db_password=$DB_PASSWORD" \
            -var "aws_demo_account_id=$AWS_DEMO_ACCOUNT" \
            -var "gcp_demo_project_id=$GCP_DEMO_PROJECT" \
            -var-file=packer/variables.pkr.hcl \
            packer/ubuntu.pkr.hcl

