name: Java CI with Maven

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USER: ${{ secrets.DB_USERNAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: health_check_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=${{ secrets.DB_PASSWORD }}" 
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up environment variables
      run: |
        echo "DB_URL=jdbc:mysql://localhost:3306/health_check_db" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    - name: Wait for MySQL
      run: |
        echo "Waiting for MySQL..."
        until mysqladmin ping -h "127.0.0.1" -u root --password=${{ secrets.DB_PASSWORD }} --silent; do
          sleep 2
        done

    - name: Validate MySQL Connection
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"
        if [ $? -ne 0 ]; then
          echo "Failed to connect to MySQL database."
          exit 1
        fi

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test
